# Blank SQL Notebook

#### Import Libraries & Database

In [3]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [3]:
%%sql

SELECT table_name
FROM information_schema.tables
where table_schema = 'public';

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

6 rows affected.

         table_name
0  currencyexchange
1          customer
2             sales
3              date
4           product
5             store

In [5]:
%%sql

SELECT *
FROM information_schema.tables;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

209 rows affected.

,table_catalog,table_schema,table_name,table_type,self_referencing_column_name,reference_generation,user_defined_type_catalog,user_defined_type_schema,user_defined_type_name,is_insertable_into,is_typed,commit_action
0,contoso_100k,public,currencyexchange,BASE TABLE,None,None,None,None,None,YES,NO,None
1,contoso_100k,public,customer,BASE TABLE,None,None,None,None,None,YES,NO,None
2,contoso_100k,public,sales,BASE TABLE,None,None,None,None,None,YES,NO,None
3,contoso_100k,public,date,BASE TABLE,None,None,None,None,None,YES,NO,None
4,contoso_100k,public,product,BASE TABLE,None,None,None,None,None,YES,NO,None
...,...,...,...,...,...,...,...,...,...,...,...,...
204,contoso_100k,information_schema,foreign_servers,VIEW,None,None,None,None,None,NO,NO,None
205,contoso_100k,information_schema,_pg_foreign_tables,VIEW,None,None,None,None,None,NO,NO,None
206,contoso_100k,information_schema,user_mapping_options,VIEW,None,None,None,None,None,NO,NO,None
207,contoso_100k,information_schema,foreign_tables,VIEW,None,None,None,None,None,NO,NO,None
208,contoso_100k,information_schema,_pg_user_mappings,VIEW,None,None,None,None,None,NO,NO,None

In [6]:
%%sql
select *
from sales
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
5,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00
6,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00
7,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00
8,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16
9,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16

In [8]:
%%sql
select *
from currencyexchange
limit 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

         date fromcurrency tocurrency  exchange
0  2015-01-01          AUD        AUD      1.00
1  2015-01-01          AUD        CAD      0.95
2  2015-01-01          AUD        EUR      0.67
3  2015-01-01          AUD        GBP      0.53
4  2015-01-01          AUD        USD      0.82
5  2015-01-01          CAD        AUD      1.05
6  2015-01-01          CAD        CAD      1.00
7  2015-01-01          CAD        EUR      0.71
8  2015-01-01          CAD        GBP      0.55
9  2015-01-01          CAD        USD      0.86

In [9]:
%%sql
select *
from store
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,storekey,storecode,geoareakey,countrycode,countryname,state,opendate,closedate,description,squaremeters,status
0,10,1,1,AU,Australia,Australian Capital Territory,2008-01-01,None,Contoso Store Australian Capital Territory,595.00,None
1,20,2,3,AU,Australia,Northern Territory,2008-01-12,2016-07-07,Contoso Store Northern Territory,665.00,Closed
2,30,3,5,AU,Australia,South Australia,2012-01-07,2015-08-08,Contoso Store South Australia,2000.00,Restructured
3,35,3,5,AU,Australia,South Australia,2015-12-08,None,Contoso Store South Australia,3000.00,None
4,40,4,6,AU,Australia,Tasmania,2010-01-01,None,Contoso Store Tasmania,2000.00,None
5,50,5,7,AU,Australia,Victoria,2015-12-09,None,Contoso Store Victoria,2000.00,None
6,60,6,8,AU,Australia,Western Australia,2010-01-01,None,Contoso Store Western Australia,2000.00,None
7,70,7,12,CA,Canada,New Brunswick,2007-05-07,2014-03-09,Contoso Store New Brunswick,1105.00,Restructured
8,72,7,12,CA,Canada,New Brunswick,2015-01-11,2018-02-02,Contoso Store New Brunswick,1500.00,Restructured
9,74,7,12,CA,Canada,New Brunswick,2018-06-02,None,Contoso Store New Brunswick,3500.00,None

In [11]:
%%sql
select *
from customer
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customerkey,geoareakey,startdt,enddt,continent,gender,title,givenname,middleinitial,surname,...,zipcode,country,countryfull,birthday,age,occupation,company,vehicle,latitude,longitude
0,15,4,1990-09-10,2034-07-29,Australia,male,Mr.,Julian,A,McGuigan,...,4357,AU,Australia,1965-03-24,55,Border Patrol agent,Cut Rite Lawn Care,2000 Peugeot Kart Up,-27.83,151.17
1,23,8,1995-08-11,2045-01-26,Australia,female,Ms.,Rose,H,Dash,...,6055,AU,Australia,1990-05-10,30,Agricultural and food scientist,Rack N Sack,2005 Volvo XC90,-31.92,116.05
2,36,2,1992-03-12,2044-05-14,Australia,female,Ms.,Annabelle,J,Townsend,...,2304,AU,Australia,1964-07-16,56,Special education teacher,id Boutiques,1999 Lancia Lybra,-32.88,151.71
3,120,6,1983-07-23,2033-08-09,Australia,male,Mr.,Jamie,H,Hetherington,...,7256,AU,Australia,1946-12-11,74,Dental laboratory technician,Showbiz Pizza Place,2006 Dodge Durango,-39.77,144.02
4,180,7,1987-11-26,2026-10-14,Australia,male,Mr.,Gabriel,P,Bosanquet,...,3505,AU,Australia,1955-04-24,65,Administrative support specialist,Dubrow's Cafeteria,1995 Morgan Plus 4,-34.13,142.14
5,185,2,1990-08-01,2029-05-28,Australia,female,Mrs.,Gabrielle,B,Castella,...,2469,AU,Australia,1980-02-23,40,Management dietitian,d.e.m.o.,1997 Alpina B6,-29.01,152.84
6,189,7,2008-07-05,2017-11-01,Australia,female,Ms.,Hayley,C,Jull,...,3377,AU,Australia,1960-04-18,60,Sculptor,Asian Plan,2006 Alpina B5,-37.34,142.91
7,210,2,1980-09-28,2030-05-08,Australia,female,Mrs.,Natalie,L,Hilder,...,2632,AU,Australia,1950-11-23,70,Motel desk clerk,Enrich Garden Services,1995 Ford Fairlane,-36.84,149.05
8,225,7,1985-06-25,2017-09-25,Australia,male,Mr.,Hunter,J,Hutchins,...,3763,AU,Australia,1978-07-20,42,Teletype operator,Mr. Good Buys,2012 Lexus GX,-37.51,145.44
9,243,2,1982-02-07,2027-02-09,Australia,female,Ms.,Maya,J,Atherton,...,2446,AU,Australia,1954-05-15,66,Pilates instructor,Franklin Music,1995 Chevrolet Caprice,-31.36,152.39

In [12]:
%%sql
select *
from product
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,productkey,productcode,productname,manufacturer,brand,color,weightunit,weight,cost,price,categorykey,categoryname,subcategorykey,subcategoryname
0,1,101001,Contoso 512MB MP3 Player E51 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.80,6.62,12.99,1,Audio,101,MP4&MP3
1,2,101002,Contoso 512MB MP3 Player E51 Blue,"Contoso, Ltd",Contoso,Blue,ounces,4.10,6.62,12.99,1,Audio,101,MP4&MP3
2,3,101003,Contoso 1G MP3 Player E100 White,"Contoso, Ltd",Contoso,White,ounces,4.50,7.40,14.52,1,Audio,101,MP4&MP3
3,4,101004,Contoso 2G MP3 Player E200 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.50,11.00,21.57,1,Audio,101,MP4&MP3
4,5,101005,Contoso 2G MP3 Player E200 Red,"Contoso, Ltd",Contoso,Red,ounces,2.40,11.00,21.57,1,Audio,101,MP4&MP3
5,6,101006,Contoso 2G MP3 Player E200 Black,"Contoso, Ltd",Contoso,Black,ounces,8.80,11.00,21.57,1,Audio,101,MP4&MP3
6,7,101007,Contoso 2G MP3 Player E200 Blue,"Contoso, Ltd",Contoso,Blue,ounces,2.10,11.00,21.57,1,Audio,101,MP4&MP3
7,8,101008,Contoso 4G MP3 Player E400 Silver,"Contoso, Ltd",Contoso,Silver,ounces,5.60,30.58,59.99,1,Audio,101,MP4&MP3
8,9,101009,Contoso 4G MP3 Player E400 Black,"Contoso, Ltd",Contoso,Black,ounces,2.10,30.58,59.99,1,Audio,101,MP4&MP3
9,10,101010,Contoso 4G MP3 Player E400 Green,"Contoso, Ltd",Contoso,Green,ounces,11.00,30.58,59.99,1,Audio,101,MP4&MP3

In [24]:
%%sql
select
  s.orderdate,
  s.quantity*s.netprice*s.exchangerate as net_revenue,
  p.productkey,
  p.categoryname,
  p.subcategoryname,
  p.productkey,
  c.customerkey,
  c.countryfull,
  c.surname,
  c.givenname,
case when s.quantity*s.netprice*s.exchangerate > 1000 then 'High' else 'low' end as high_low
from
  sales s
left join product p on s.productkey = p.productkey
left join customer c on s.customerkey = c.customerkey
where orderdate::date >= '2020-01-01'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

124451 rows affected.

,orderdate,net_revenue,productkey,categoryname,subcategoryname,productkey,customerkey,countryfull,surname,givenname,high_low
0,2020-01-01,99.47,1810,Games and Toys,Download Games,1810,593517,Germany,Burger,Heike,low
1,2020-01-01,139.97,1809,Games and Toys,Download Games,1809,593517,Germany,Burger,Heike,low
2,2020-01-01,669.39,698,Computers,"Printers, Scanners & Fax",698,593517,Germany,Burger,Heike,low
3,2020-01-01,4090.60,364,Computers,Laptops,364,593517,Germany,Burger,Heike,High
4,2020-01-01,5590.00,451,Computers,Desktops,451,1567083,United States,Frye,James,High
...,...,...,...,...,...,...,...,...,...,...,...
124446,2024-04-20,914.61,1651,"Music, Movies and Audio Books",Movie DVD,1651,664396,France,Rivière,Karlotta,low
124447,2024-04-20,150.18,1646,"Music, Movies and Audio Books",Movie DVD,1646,664396,France,Rivière,Karlotta,low
124448,2024-04-20,147.78,1575,"Music, Movies and Audio Books",Movie DVD,1575,267690,Canada,Wilson,Michael,low
124449,2024-04-20,2019.62,415,Computers,Laptops,415,267690,Canada,Wilson,Michael,High
124450,2024-04-20,56.83,1693,Games and Toys,Boxed Games,1693,267690,Canada,Wilson,Michael,low

Warning: total number of rows (124451) exceeds max_rows (20000). Limiting to first (20000) rows.

In [40]:
%%sql

select
s.orderdate,
count(distinct s.customerkey),
count(distinct case when c.continent = 'Europe' then s.customerkey end) as eu_customers,
count(distinct case when c.continent = 'North America' then s.customerkey end) as na_customers,
count(distinct case when c.continent = 'Australia' then s.customerkey end) as au_customers
from sales s
left join customer c on s.customerkey = c.customerkey
where s.orderdate between '2023-01-01' and '2023-12-31'
group by s.orderdate
order by s.orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

364 rows affected.

      orderdate  count  eu_customers  na_customers  au_customers
0    2023-01-01     12             6             5             1
1    2023-01-02     49            15            31             3
2    2023-01-03     64            17            44             3
3    2023-01-04     78            28            46             4
4    2023-01-05     87            22            57             8
..          ...    ...           ...           ...           ...
359  2023-12-27     73            26            41             6
360  2023-12-28     75            24            44             7
361  2023-12-29     55            19            32             4
362  2023-12-30     91            25            50            16
363  2023-12-31      9             1             8             0

[364 rows x 5 columns]

In [52]:
%%sql
select
  p.categoryname,
  --sum(s.quantity*s.netprice*s.exchangerate) as net_revenue,
  sum(case when s.orderdate between '2022-01-01' and '2022-12-31' then s.quantity*s.netprice*s.exchangerate else 0 end) as revenue_2022,
  sum(case when s.orderdate between '2023-01-01' and '2023-12-31' then s.quantity*s.netprice*s.exchangerate else 0 end) as revenue_2023
from
  sales s
left join product p on p.productkey = s.productkey
group by p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname  revenue_2022  revenue_2023
0                          Audio     766938.21     688690.18
1        Cameras and camcorders     2382532.56    1983546.29
2                    Cell phones    8119665.07    6002147.63
3                      Computers   17862213.49   11650867.21
4                 Games and Toys     316127.30     270374.96
5                Home Appliances    6612446.68    5919992.87
6  Music, Movies and Audio Books    2989297.28    2180768.13
7                   TV and Video    5815336.61    4412178.23

In [51]:
%%sql
select
  p.categoryname,
  sum(s.quantity*s.netprice*s.exchangerate) as net_revenue
  -- sum(case when s.orderdate between '2022-01-01' and '2022-12-31' then s.quantity*s.netprice*s.exchangerate else 0 end) as revenue_2022,
  -- sum(case when s.orderdate between '2023-01-01' and '2023-12-31' then s.quantity*s.netprice*s.exchangerate else 0 end) as revenue_2023
from
  sales s
left join product p on p.productkey = s.productkey
where s.orderdate between '2022-01-01' and '2023-12-31'
group by p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname  net_revenue
0                          Audio   1455628.40
1        Cameras and camcorders    4366078.85
2                    Cell phones  14121812.71
3                      Computers  29513080.70
4                 Games and Toys    586502.27
5                Home Appliances  12532439.55
6  Music, Movies and Audio Books   5170065.41
7                   TV and Video  10227514.83

In [58]:
%%sql
select
  percentile_cont(0.0) within group (order by netprice) as median,
  percentile_cont(0.25) within group (order by netprice) as median,
  percentile_cont(0.50) within group (order by netprice) as median,
  percentile_cont(0.75) within group (order by netprice) as median,
  AVG(netprice)
from
sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   median  median  median  median    avg
0    0.82   46.72  191.95  395.91 324.30

In [63]:
%%sql

select
p.categoryname,
PERCENTILE_CONT(0.5) within group  (order by (case when s.orderdate between '2022-01-01' and '2022-12-31' then s.quantity*s.netprice*s.exchangerate end)) as y2022_median,
PERCENTILE_CONT(0.5) within group  (order by (case when s.orderdate between '2023-01-01' and '2023-12-31' then s.quantity*s.netprice*s.exchangerate end)) as y2023_median

from sales s
left join product p on s.productkey = p.productkey
group by p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname  y2022_median  y2023_median
0                          Audio        257.21        266.59
1        Cameras and camcorders         651.46        672.60
2                    Cell phones        418.60        375.88
3                      Computers        809.70        657.18
4                 Games and Toys         33.78         32.62
5                Home Appliances        791.00        825.25
6  Music, Movies and Audio Books        186.58        159.63
7                   TV and Video        730.46        790.79

In [6]:
%%sql
select
  PERCENTILE_CONT(0.50) within group (order by (s.quantity*s.netprice*s.exchangerate)) as median
from sales s
left join product p on p.productkey = s.productkey

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   median
0  399.17

In [21]:
%%sql
with cte as (
select
  PERCENTILE_CONT(0.50) within group (order by (s.quantity*s.netprice*s.exchangerate)) as median
from sales s
where s.orderdate between '2022-01-01' and '2023-12-31'
)


select
  p.categoryname,
  sum(s.quantity*s.netprice*s.exchangerate) as net_revenue,
  SUM(case when (s.quantity*s.netprice*s.exchangerate) < (select median from cte)
    and (s.orderdate between '2022-01-01' and '2022-12-31')
    then (s.quantity*s.netprice*s.exchangerate) end ) as low_net_revenue_2022,
  SUM(case when (s.quantity*s.netprice*s.exchangerate) >= (select median from cte)
    and (s.orderdate between '2022-01-01' and '2022-12-31')
    then (s.quantity*s.netprice*s.exchangerate) end ) as high_net_revenue_2022
from sales s
left join product p on p.productkey = s.productkey
group by p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,net_revenue,low_net_revenue_2022,high_net_revenue_2022
0,Audio,5312898.10,222337.83,544600.39
1,Cameras and camcorders,18520360.66,133004.54,2249528.02
2,Cell phones,32624265.72,814449.53,7305215.55
3,Computers,90619022.05,624340.42,17237873.07
4,Games and Toys,1668574.13,231979.63,84147.67
5,Home Appliances,26607245.54,219797.07,6392649.61
6,"Music, Movies and Audio Books",10588311.00,685808.49,2303488.80
7,TV and Video,20466861.38,272338.29,5542998.32

In [9]:
%%sql

SELECT
    PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (s.quantity * s.netprice * s.exchangerate)) AS median
FROM
    sales s
WHERE
    orderdate BETWEEN '2022-01-01' AND '2023-12-31'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   median
0  398.00

In [10]:
%%sql
select
  PERCENTILE_CONT(0.50) within group (order by (s.quantity*s.netprice*s.exchangerate)) as median
from sales s

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   median
0  399.17

In [20]:
%%sql
with cte as (
  select
    PERCENTILE_CONT(0.25) within group(order by (s.quantity*s.netprice*s.exchangerate)) as low_percentile,
    PERCENTILE_CONT(0.75) within group(order by (s.quantity*s.netprice*s.exchangerate)) as high_percentile
  from sales s
  where s.orderdate between '2022-01-01' AND '2023-12-31'
)

select
p.categoryname,
sum(s.quantity*s.netprice*s.exchangerate) as total_revenue,
case
  when (s.quantity*s.netprice*s.exchangerate) <= cte.low_percentile then '3-low'
  when (s.quantity*s.netprice*s.exchangerate) >= cte.high_percentile then  '1-high'
  else '2-medium' end as teir
from sales s
left join product p on p.productkey = s.productkey, cte

group by p.categoryname, teir
order by p.categoryname, teir

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

24 rows affected.

                     categoryname  total_revenue      teir
0                           Audio     1213265.71    1-high
1                           Audio     3832415.38  2-medium
2                           Audio      267217.01     3-low
3         Cameras and camcorders     15050781.63    1-high
4         Cameras and camcorders      3388546.10  2-medium
5         Cameras and camcorders        81032.92     3-low
6                     Cell phones    21874993.15    1-high
7                     Cell phones    10338963.22  2-medium
8                     Cell phones      410309.35     3-low
9                       Computers    79607760.89    1-high
10                      Computers    10808054.11  2-medium
11                      Computers      203207.06     3-low
12                 Games and Toys      133749.09    1-high
13                 Games and Toys     1001381.91  2-medium
14                 Games and Toys      533443.13     3-low
15                Home Appliances    22383475.30    1-high
16                Home Appliances     4118724.64  2-medium
17                Home Appliances      105045.60     3-low
18  Music, Movies and Audio Books     3844996.29    1-high
19  Music, Movies and Audio Books     6100817.99  2-medium
20  Music, Movies and Audio Books      642496.71     3-low
21                   TV and Video    16632856.33    1-high
22                   TV and Video     3766783.30  2-medium
23                   TV and Video       67221.76     3-low

In [9]:
%%sql

select
    s.orderdate,
    PERCENTILE_CONT(0.25) within group(order by (s.quantity*s.netprice*s.exchangerate)) as low_percentile,
    PERCENTILE_CONT(0.75) within group(order by (s.quantity*s.netprice*s.exchangerate)) as high_percentile
  from sales s
  group by orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

3294 rows affected.

       orderdate  low_percentile  high_percentile
0     2015-01-01           63.29           578.52
1     2015-01-02          233.93           885.22
2     2015-01-03          117.97           563.47
3     2015-01-05          166.11          1720.86
4     2015-01-06           55.38           947.79
...          ...             ...              ...
3289  2024-04-16           96.96           533.44
3290  2024-04-17           92.99           771.42
3291  2024-04-18          114.98           752.78
3292  2024-04-19          110.35          1174.13
3293  2024-04-20           80.83           674.86

[3294 rows x 3 columns]